### ISSUE TITLE
VSCode Tach output: (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')) on MacBook Pro 16 2019 (intel)

### ISSUE THREAD

**Issue by dorozhkoanton** [gauge-sh/tach-vscode#10]
Installed on VSCode
Run the command Tach: Restart server

Error message:
```
2024-11-22 10:10:50.754 [info] Server run command: /Users/dorozhkoanton/Projects/Python/FastAPI/BillBook/.venv/bin/python /Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.3-darwin-x64/bundled/tool/lsp_server.py
2024-11-22 10:10:50.754 [info] Server: Start requested.
2024-11-22 10:10:51.449 [info] Traceback (most recent call last):

2024-11-22 10:10:51.450 [info]   File "/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.3-darwin-x64/bundled/tool/lsp_server.py", line 45, in <module>
    from tach_util import run_tach_check  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.3-darwin-x64/bundled/tool/tach_util.py", line 4, in <module>
    from tach.extension import check
ImportError: dlopen(/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.3-darwin-x64/bundled/libs/tach/extension.cpython-313-darwin.so, 0x0002): tried: '/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.3-darwin-x64/bundled/libs/tach/extension.cpython-313-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.3-darwin-x64/bundled/libs/tach/extension.cpython-313-darwin.so' (no such file), '/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.3-darwin-x64/bundled/libs/tach/extension.cpython-313-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))

2024-11-22 10:10:51.503 [info] [Error - 10:10:51] Server initialization failed.
2024-11-22 10:10:51.503 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-11-22 10:10:51.503 [info] [Info  - 10:10:51] Connection to server got closed. Server will restart.
```

Tach works correctly via CLI

Tach extension version: v0.14.3
Tach version: 0.15.1

MacBook Pro 16 2019 (intel)
VSCode version:
```
code --version
1.95.3
f1a4fb101478ce6ec82fe9627c43efbf9e98c813
x64
```

**Comment by emdoyle** [comment]
Thanks for raising this! I think I see the issue in our publish action, it looks like the Mac x64 build is just using `macos-latest`, which I'm guessing is an ARM Mac. I'll see if we can re-publish under the same tag, otherwise I will post back here with a fixed version number.

**Comment by emdoyle** [comment]
Just released the build change. Please let me know if upgrading the extension to the latest version (0.14.4) fixes this issue! @dorozhkoanton

**Comment by dorozhkoanton** [comment]
I updated to the new version, and it's working! Thank you so much for your help! @emdoyle
