### ISSUE TITLE
The Tach extension currently does not support the `interfaces = []` field in the `tach.toml` file.

### ISSUE THREAD

**Issue by dorozhkoanton** [gauge-sh/tach-vscode#12]
If you run `tach mod`, it generates a `tach.toml` file with `interfaces = []` field included by default. However, when the extension attempts to load this configuration, it raises an exception:

```
2024-11-24 11:04:12.628 [info] Name: Tach
2024-11-24 11:04:12.628 [info] Module: tach
2024-11-24 11:04:12.628 [info] Python extension loading
2024-11-24 11:04:12.628 [info] Waiting for interpreter from python extension.
2024-11-24 11:04:12.628 [info] Python extension loaded
2024-11-24 11:04:12.628 [info] Server run command: /Users/dorozhkoanton/Projects/Python/FastAPI/bill-bool-app/.venv/bin/python /Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.4-darwin-x64/bundled/tool/lsp_server.py
2024-11-24 11:04:12.628 [info] Server: Start requested.
2024-11-24 11:04:13.213 [info] Traceback (most recent call last):

2024-11-24 11:04:13.213 [info]   File "/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.4-darwin-x64/bundled/tool/lsp_server.py", line 45, in <module>
    from tach_util import run_tach_check  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.4-darwin-x64/bundled/tool/tach_util.py", line 6, in <module>
    from tach.cli import parse_arguments
  File "/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.4-darwin-x64/bundled/libs/tach/cli.py", line 28, in <module>
    from tach.logging import LogDataModel, logger
  File "/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.4-darwin-x64/bundled/libs/tach/logging/__init__.py", line 3, in <module>
    from tach.logging.logger import LogDataModel, logger
  File "/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.4-darwin-x64/bundled/libs/tach/logging/logger.py", line 89, in <module>
    project_config = parse_project_config()
  File "/Users/dorozhkoanton/.vscode/extensions/gauge.tach-0.14.4-darwin-x64/bundled/libs/tach/parsing/config.py", line 66, in parse_project_config
    project_config = ext_parse_project_config(file_path)
ValueError: TOML parse error at line 1, column 1
  |
1 | interfaces = []
  | ^^^^^^^^^^
unknown field `interfaces`, expected one of `modules`, `cache`, `external`, `exclude`, `source_roots`, `exact`, `disable_logging`, `ignore_type_checking_imports`, `forbid_circular_dependencies`, `use_regex_matching`, `root_module`


2024-11-24 11:04:13.267 [info] [Error - 11:04:13] Server initialization failed.
2024-11-24 11:04:13.267 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-11-24 11:04:13.267 [info] [Info  - 11:04:13] Connection to server got closed. Server will restart.
```

As a workaround, deleting the `interfaces = []` field from the `tach.toml` file resolves the issue, allowing the Tach extension to function normally.

Extension version: 0.14.4
Tach version: 0.15.2

VSCode version: 1.95.3
f1a4fb101478ce6ec82fe9627c43efbf9e98c813
x64

**Comment by emdoyle** [comment]
Thanks for calling this out! Will ship a 0.15.x release today and post back here when it is available.

**Comment by emdoyle** [comment]
Release `0.15.3` is now available and should resolve this failure. However, it doesn't include support for checking interface violations yet.

Please let me know if it works for you!

I also found a couple other issues that I'll discuss in a separate thread.

**Comment by dorozhkoanton** [comment]
The extension is now functioning perfectly without any exceptions. Thank you so much for your help!

I also wanted to sincerely thank you for this amazing product! It’s incredibly useful for me, and I’m sure for many other developers and teams as well. I’m confident that Tach will become very popular soon!

In fact, I’ve already shared it in a chat with the Python core developer @sobolevn, and many people there appreciated it, especially the features `tach mod`, `tach show --web`, and the availability of the VS Code extension. Wishing you great success with Tach, and thank you once again for your support!

**Comment by emdoyle** [comment]
Thank you very much @dorozhkoanton for the kind words, and for your support in sharing Tach! I'm excited to continue improving it and I appreciate your engagement and feedback here.
